#!/bin/bash

# SpeedyCRM Orphaned Files Cleanup Script
# Generated: 2025-12-09
# BACKUP FIRST: git commit -am "Backup before cleanup"

echo "🧹 SpeedyCRM Orphaned Files Cleanup - Phase 2"
echo "=============================================="
echo ""
echo "⚠️  WARNING: This will DELETE orphaned files"
echo "📦 Make sure you have a backup commit!"
echo ""
echo "Files to be deleted:"
echo "  - 10 migration/utility scripts"
echo "  - 41 orphaned standalone pages"
echo "  - 1 restore directory"
echo ""
read -p "Continue? (yes/no): " confirm

if [ "$confirm" != "yes" ]; then
    echo "❌ Aborted."
    exit 1
fi

# Navigate to project root
cd /home/user/my-clever-crm

echo ""
echo "🔄 Deleting migration/utility scripts..."
rm -f src/utils/createCollections.js && echo "  ✅ Deleted createCollections.js"
rm -f src/utils/seedProducts.js && echo "  ✅ Deleted seedProducts.js"
rm -f src/utils/initializeDisputeCollection.js && echo "  ✅ Deleted initializeDisputeCollection.js"
rm -f src/utils/initSocialCollections.js && echo "  ✅ Deleted initSocialCollections.js"
rm -f src/utils/fixProcessedField.js && echo "  ✅ Deleted fixProcessedField.js"
rm -f src/utils/migrateToAutomatedPipeline.js && echo "  ✅ Deleted migrateToAutomatedPipeline.js"
rm -f src/utils/migrateLeads.js && echo "  ✅ Deleted migrateLeads.js"
rm -f src/utils/reprocessCallerNames.js && echo "  ✅ Deleted reprocessCallerNames.js"
rm -f src/utils/processExistingCalls.js && echo "  ✅ Deleted processExistingCalls.js"
rm -f src/utils/fixAllCallerNames.js && echo "  ✅ Deleted fixAllCallerNames.js"

echo ""
echo "🔄 Deleting orphaned standalone pages (replaced by Hubs)..."
rm -f src/pages/AICommandCenter.jsx && echo "  ✅ Deleted AICommandCenter.jsx (replaced by AIHub)"
rm -f src/pages/AIReceptionist.jsx && echo "  ✅ Deleted AIReceptionist.jsx (replaced by AIHub)"
rm -f src/pages/AddClient.jsx && echo "  ✅ Deleted AddClient.jsx (replaced by ClientsHub)"
rm -f src/pages/AdminAddendumFlow.jsx && echo "  ✅ Deleted AdminAddendumFlow.jsx (replaced by Addendums)"
rm -f src/pages/AdminTools.jsx && echo "  ✅ Deleted AdminTools.jsx (replaced by Portal)"
rm -f src/pages/Administration.jsx && echo "  ✅ Deleted Administration.jsx (replaced by SettingsHub)"
rm -f src/pages/AllActivityLog.jsx && echo "  ✅ Deleted AllActivityLog.jsx (replaced by ReportsHub)"
rm -f src/pages/Automation.jsx && echo "  ✅ Deleted Automation.jsx (replaced by AutomationHub)"
rm -f src/pages/Bulk.jsx && echo "  ✅ Deleted Bulk.jsx (replaced by ClientsHub)"
rm -f src/pages/ClientList.jsx && echo "  ✅ Deleted ClientList.jsx (replaced by ClientsHub)"
rm -f src/pages/ClientManagement.jsx && echo "  ✅ Deleted ClientManagement.jsx (replaced by ClientsHub)"
rm -f src/pages/ClientProfile.jsx && echo "  ✅ Deleted ClientProfile.jsx (replaced by ContactDetailPage)"
rm -f src/pages/ClientReports.jsx && echo "  ✅ Deleted ClientReports.jsx (replaced by ReportsHub)"
rm -f src/pages/CommunicationsCenter.jsx && echo "  ✅ Deleted CommunicationsCenter.jsx (replaced by CommunicationsHub)"
rm -f src/pages/Dashboard.jsx && echo "  ✅ Deleted Dashboard.jsx (replaced by SmartDashboard)"
rm -f src/pages/DisputeCenter.jsx && echo "  ✅ Deleted DisputeCenter.jsx (replaced by DisputeHub)"
rm -f src/pages/DisputeCreation.jsx && echo "  ✅ Deleted DisputeCreation.jsx (replaced by DisputeHub)"
rm -f src/pages/Disputes.jsx && echo "  ✅ Deleted Disputes.jsx (replaced by DisputeHub)"
rm -f src/pages/EditClient.jsx && echo "  ✅ Deleted EditClient.jsx (replaced by ClientsHub)"
rm -f src/pages/Export.jsx && echo "  ✅ Deleted Export.jsx (replaced by ContactExport)"
rm -f src/pages/FeaturesTutorials.jsx && echo "  ✅ Deleted FeaturesTutorials.jsx (replaced by LearningHub)"
rm -f src/pages/Help.jsx && echo "  ✅ Deleted Help.jsx (replaced by SupportHub)"
rm -f src/pages/ImportCSV.jsx && echo "  ✅ Deleted ImportCSV.jsx (replaced by ContactImport)"
rm -f src/pages/KnowledgeBase.jsx && echo "  ✅ Deleted KnowledgeBase.jsx (replaced by ResourceLibraryHub)"
rm -f src/pages/Leads.jsx && echo "  ✅ Deleted Leads.jsx (replaced by ClientsHub)"
rm -f src/pages/LeadsPage.jsx && echo "  ✅ Deleted LeadsPage.jsx (replaced by ClientsHub)"
rm -f src/pages/LiveTrainingSessions.jsx && echo "  ✅ Deleted LiveTrainingSessions.jsx (hub version kept)"
rm -f src/pages/Logout.jsx && echo "  ✅ Deleted Logout.jsx (handled by auth context)"
rm -f src/pages/ManageRoles.jsx && echo "  ✅ Deleted ManageRoles.jsx (replaced by Roles page)"
rm -f src/pages/Messages.jsx && echo "  ✅ Deleted Messages.jsx (replaced by CommunicationsHub)"
rm -f src/pages/OnboardingWizard.jsx && echo "  ✅ Deleted OnboardingWizard.jsx (hub version kept)"
rm -f src/pages/OpenAI.jsx && echo "  ✅ Deleted OpenAI.jsx (replaced by AIHub)"
rm -f src/pages/Permissions.jsx && echo "  ✅ Deleted Permissions.jsx (replaced by SettingsHub)"
rm -f src/pages/ProgressPortal.jsx && echo "  ✅ Deleted ProgressPortal.jsx (hub version kept)"
rm -f src/pages/ProgressTracker.jsx && echo "  ✅ Deleted ProgressTracker.jsx (hub version kept)"
rm -f src/pages/Referrals.jsx && echo "  ✅ Deleted Referrals.jsx (replaced by ReferralEngineHub)"
rm -f src/pages/RoleBasedTraining.jsx && echo "  ✅ Deleted RoleBasedTraining.jsx (hub version kept)"
rm -f src/pages/ScoreSimulator.jsx && echo "  ✅ Deleted ScoreSimulator.jsx (replaced by CreditSimulator)"
rm -f src/pages/Setup.jsx && echo "  ✅ Deleted Setup.jsx (onboarding handled elsewhere)"
rm -f src/pages/Simulator.jsx && echo "  ✅ Deleted Simulator.jsx (replaced by CreditSimulator)"
rm -f src/pages/SkinSwitcher.jsx && echo "  ✅ Deleted SkinSwitcher.jsx (skins version kept)"
rm -f src/pages/SocialMediaAdmin.jsx && echo "  ✅ Deleted SocialMediaAdmin.jsx (replaced by SocialMediaHub)"
rm -f src/pages/TrainingLibrary.jsx && echo "  ✅ Deleted TrainingLibrary.jsx (hub version kept)"
rm -f src/pages/WorkflowBuilder.jsx && echo "  ✅ Deleted WorkflowBuilder.jsx (replaced by AutomationHub)"

echo ""
echo "🔄 Deleting orphaned restore directory..."
rm -rf src/pages/restore/ && echo "  ✅ Deleted restore directory"

echo ""
echo "✅ CLEANUP COMPLETE!"
echo ""
echo "📊 Summary:"
echo "  • 10 migration scripts deleted"
echo "  • 41 orphaned pages deleted"
echo "  • 1 restore directory deleted"
echo "  • Total: 52 files deleted"
echo ""
echo "🎯 Next steps:"
echo "  1. Test the application: npm run dev"
echo "  2. Build production: npm run build"
echo "  3. Commit changes: git add -A && git commit -m 'chore: remove orphaned files (Phase 2 cleanup)'"
echo ""
echo "💡 Files kept for review:"
echo "  • AuthDebug.jsx (dev tool)"
echo "  • DatabaseDiagnostic.jsx (admin tool)"
echo "  • TestRunner.jsx (QA tool)"
echo "  • NotFound.jsx (needs routing)"
echo "  • Unauthorized.jsx (needs routing)"
echo "  • Profile.jsx (verify SettingsHub coverage)"
echo ""
