// Firestore Dispute data model example
// This file is for reference/documentation only.
// Each dispute document in the 'disputes' collection might look like:
// {
//   id: string (Firestore doc id),
//   userId: string (owner),
//   creditor: string,
//   accountNumber: string,
//   status: 'open' | 'in-progress' | 'resolved',
//   openedAt: Timestamp,
//   updatedAt: Timestamp,
//   notes: string,
//   aiLetter: string (optional, generated by AI)
// }
